implementation of global indent class
unknown cause of
  TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

when using the reference for the global indentation